# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "78913995e14ddaac9bcc4ae2afa9801b"
name = "Product Stats Assignment"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
handle = "shopify-product-stats"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
